const Pokedex = {
    "Bulbasaur": {
        name: "Bulbasaur",
        types: ["Grass", "Poison"],
        preevolution: [],
        evolution: ["Ivysaur"],
    },
    "Ivysaur": {
        name: "Ivysaur",
        types: ["Grass", "Poison"],
        preevolution: ["Bulbasaur"],
        evolution: ["Venusaur"],
    },
    "Venusaur": {
        name: "Venusaur",
        types: ["Grass", "Poison"],
        preevolution: ["Ivysaur"],
        evolution: [],
    },
    "Charmander": {
        name: "Charmander",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Charmeleon"],
    },
    "Charmeleon": {
        name: "Charmeleon",
        types: ["Fire"],
        preevolution: ["Charmander"],
        evolution: ["Charizard"],
    },
    "Charizard": {
        name: "Charizard",
        types: ["Fire", "Flying"],
        preevolution: ["Charmeleon"],
        evolution: [],
    },
    "Squirtle": {
        name: "Squirtle",
        types: ["Water"],
        preevolution: [],
        evolution: ["Wartortle"],
    },
    "Wartortle": {
        name: "Wartortle",
        types: ["Water"],
        preevolution: ["Squirtle"],
        evolution: ["Blastoise"],
    },
    "Blastoise": {
        name: "Blastoise",
        types: ["Water"],
        preevolution: ["Wartortle"],
        evolution: [],
    },
    "Caterpie": {
        name: "Caterpie",
        types: ["Bug"],
        preevolution: [],
        evolution: ["Metapod"],
    },
    "Metapod": {
        name: "Metapod",
        types: ["Bug"],
        preevolution: ["Caterpie"],
        evolution: ["Butterfree"],
    },
    "Butterfree": {
        name: "Butterfree",
        types: ["Bug", "Flying"],
        preevolution: ["Metapod"],
        evolution: [],
    },
    "Weedle": {
        name: "Weedle",
        types: ["Bug", "Poison"],
        preevolution: [],
        evolution: ["Kakuna"],
    },
    "Kakuna": {
        name: "Kakuna",
        types: ["Bug", "Poison"],
        preevolution: ["Weedle"],
        evolution: ["Beedrill"],
    },
    "Beedrill": {
        name: "Beedrill",
        types: ["Bug", "Poison"],
        preevolution: ["Kakuna"],
        evolution: [],
    },
    "Pidgey": {
        name: "Pidgey",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Pidgeotto"],
    },
    "Pidgeotto": {
        name: "Pidgeotto",
        types: ["Normal", "Flying"],
        preevolution: ["Pidgey"],
        evolution: ["Pidgeot"],
    },
    "Pidgeot": {
        name: "Pidgeot",
        types: ["Normal", "Flying"],
        preevolution: ["Pidgeotto"],
        evolution: [],
    },
    "Rattata": {
        name: "Rattata",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Raticate"],
    },
    "Raticate": {
        name: "Raticate",
        types: ["Normal"],
        preevolution: ["Rattata"],
        evolution: [],
    },
    "Spearow": {
        name: "Spearow",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Fearow"],
    },
    "Fearow": {
        name: "Fearow",
        types: ["Normal", "Flying"],
        preevolution: ["Spearow"],
        evolution: [],
    },
    "Ekans": {
        name: "Ekans",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Arbok"],
    },
    "Arbok": {
        name: "Arbok",
        types: ["Poison"],
        preevolution: ["Ekans"],
        evolution: [],
    },
    "Pikachu": {
        name: "Pikachu",
        types: ["Electric"],
        preevolution: ["Pichu"],
        evolution: ["Raichu"],
    },
    "Raichu": {
        name: "Raichu",
        types: ["Electric"],
        preevolution: ["Pikachu"],
        evolution: [],
    },
    "Sandshrew": {
        name: "Sandshrew",
        types: ["Ground"],
        preevolution: [],
        evolution: ["Sandslash"],
    },
    "Sandslash": {
        name: "Sandslash",
        types: ["Ground"],
        preevolution: ["Sandshrew"],
        evolution: [],
    },
    "Nidoran (F)": {
        name: "Nidoran (F)",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Nidorina"],
    },
    "Nidorina": {
        name: "Nidorina",
        types: ["Poison"],
        preevolution: ["Nidoran (F)"],
        evolution: ["Nidoqueen"],
    },
    "Nidoqueen": {
        name: "Nidoqueen",
        types: ["Poison", "Ground"],
        preevolution: ["Nidorina"],
        evolution: [],
    },
    "Nidoran (M)": {
        name: "Nidoran (M)",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Nidorino"],
    },
    "Nidorino": {
        name: "Nidorino",
        types: ["Poison"],
        preevolution: ["Nidoran (M)"],
        evolution: ["Nidoking"],
    },
    "Nidoking": {
        name: "Nidoking",
        types: ["Poison", "Ground"],
        preevolution: ["Nidorino"],
        evolution: [],
    },
    "Clefairy": {
        name: "Clefairy",
        types: ["Normal"],
        preevolution: ["Cleffa"],
        evolution: ["Clefable"],
    },
    "Clefable": {
        name: "Clefable",
        types: ["Normal"],
        preevolution: ["Clefairy"],
        evolution: [],
    },
    "Vulpix": {
        name: "Vulpix",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Ninetales"],
    },
    "Ninetales": {
        name: "Ninetales",
        types: ["Fire"],
        preevolution: ["Vulpix"],
        evolution: [],
    },
    "Jigglypuff": {
        name: "Jigglypuff",
        types: ["Normal"],
        preevolution: ["Igglybuff"],
        evolution: ["Wigglytuff"],
    },
    "Wigglytuff": {
        name: "Wigglytuff",
        types: ["Normal"],
        preevolution: ["Jigglypuff"],
        evolution: [],
    },
    "Zubat": {
        name: "Zubat",
        types: ["Poison", "Flying"],
        preevolution: [],
        evolution: ["Golbat"],
    },
    "Golbat": {
        name: "Golbat",
        types: ["Poison", "Flying"],
        preevolution: ["Zubat"],
        evolution: ["Crobat"],
    },
    "Oddish": {
        name: "Oddish",
        types: ["Grass", "Poison"],
        preevolution: [],
        evolution: ["Gloom"],
    },
    "Gloom": {
        name: "Gloom",
        types: ["Grass", "Poison"],
        preevolution: ["Oddish"],
        evolution: ["Vileplume", "Bellossom"],
    },
    "Vileplume": {
        name: "Vileplume",
        types: ["Grass", "Poison"],
        preevolution: ["Gloom"],
        evolution: [],
    },
    "Paras": {
        name: "Paras",
        types: ["Bug", "Grass"],
        preevolution: [],
        evolution: ["Parasect"],
    },
    "Parasect": {
        name: "Parasect",
        types: ["Bug", "Grass"],
        preevolution: ["Paras"],
        evolution: [],
    },
    "Venonat": {
        name: "Venonat",
        types: ["Bug", "Poison"],
        preevolution: [],
        evolution: ["Venomoth"],
    },
    "Venomoth": {
        name: "Venomoth",
        types: ["Bug", "Poison"],
        preevolution: ["Venonat"],
        evolution: [],
    },
    "Diglett": {
        name: "Diglett",
        types: ["Ground"],
        preevolution: [],
        evolution: ["Dugtrio"],
    },
    "Dugtrio": {
        name: "Dugtrio",
        types: ["Ground"],
        preevolution: ["Diglett"],
        evolution: [],
    },
    "Meowth": {
        name: "Meowth",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Persian"],
    },
    "Persian": {
        name: "Persian",
        types: ["Normal"],
        preevolution: ["Meowth"],
        evolution: [],
    },
    "Psyduck": {
        name: "Psyduck",
        types: ["Water"],
        preevolution: [],
        evolution: ["Golduck"],
    },
    "Golduck": {
        name: "Golduck",
        types: ["Water"],
        preevolution: ["Psyduck"],
        evolution: [],
    },
    "Mankey": {
        name: "Mankey",
        types: ["Fighting"],
        preevolution: [],
        evolution: ["Primeape"],
    },
    "Primeape": {
        name: "Primeape",
        types: ["Fighting"],
        preevolution: ["Mankey"],
        evolution: [],
    },
    "Growlithe": {
        name: "Growlithe",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Arcanine"],
    },
    "Arcanine": {
        name: "Arcanine",
        types: ["Fire"],
        preevolution: ["Growlithe"],
        evolution: [],
    },
    "Poliwag": {
        name: "Poliwag",
        types: ["Water"],
        preevolution: [],
        evolution: ["Poliwhirl"],
    },
    "Poliwhirl": {
        name: "Poliwhirl",
        types: ["Water"],
        preevolution: ["Poliwag"],
        evolution: ["Poliwrath", "Politoed"],
    },
    "Poliwrath": {
        name: "Poliwrath",
        types: ["Water", "Fighting"],
        preevolution: ["Poliwhirl"],
        evolution: [],
    },
    "Abra": {
        name: "Abra",
        types: ["Psychic"],
        preevolution: [],
        evolution: ["Kadabra"],
    },
    "Kadabra": {
        name: "Kadabra",
        types: ["Psychic"],
        preevolution: ["Abra"],
        evolution: ["Alakazam"],
    },
    "Alakazam": {
        name: "Alakazam",
        types: ["Psychic"],
        preevolution: ["Kadabra"],
        evolution: [],
    },
    "Machop": {
        name: "Machop",
        types: ["Fighting"],
        preevolution: [],
        evolution: ["Machoke"],
    },
    "Machoke": {
        name: "Machoke",
        types: ["Fighting"],
        preevolution: ["Machop"],
        evolution: ["Machamp"],
    },
    "Machamp": {
        name: "Machamp",
        types: ["Fighting"],
        preevolution: ["Machoke"],
        evolution: [],
    },
    "Bellsprout": {
        name: "Bellsprout",
        types: ["Grass", "Poison"],
        preevolution: [],
        evolution: ["Weepinbell"],
    },
    "Weepinbell": {
        name: "Weepinbell",
        types: ["Grass", "Poison"],
        preevolution: ["Bellsprout"],
        evolution: ["Victreebel"],
    },
    "Victreebel": {
        name: "Victreebel",
        types: ["Grass", "Poison"],
        preevolution: ["Weepinbell"],
        evolution: [],
    },
    "Tentacool": {
        name: "Tentacool",
        types: ["Water", "Poison"],
        preevolution: [],
        evolution: ["Tentacruel"],
    },
    "Tentacruel": {
        name: "Tentacruel",
        types: ["Water", "Poison"],
        preevolution: ["Tentacool"],
        evolution: [],
    },
    "Geodude": {
        name: "Geodude",
        types: ["Rock", "Ground"],
        preevolution: [],
        evolution: ["Graveler"],
    },
    "Graveler": {
        name: "Graveler",
        types: ["Rock", "Ground"],
        preevolution: ["Geodude"],
        evolution: ["Golem"],
    },
    "Golem": {
        name: "Golem",
        types: ["Rock", "Ground"],
        preevolution: ["Graveler"],
        evolution: [],
    },
    "Ponyta": {
        name: "Ponyta",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Rapidash"],
    },
    "Rapidash": {
        name: "Rapidash",
        types: ["Fire"],
        preevolution: ["Ponyta"],
        evolution: [],
    },
    "Slowpoke": {
        name: "Slowpoke",
        types: ["Water", "Psychic"],
        preevolution: [],
        evolution: ["Slowbro", "Slowking"],
    },
    "Slowbro": {
        name: "Slowbro",
        types: ["Water", "Psychic"],
        preevolution: ["Slowpoke"],
        evolution: [],
    },
    "Magnemite": {
        name: "Magnemite",
        types: ["Electric", "Steel"],
        preevolution: [],
        evolution: ["Magneton"],
    },
    "Magneton": {
        name: "Magneton",
        types: ["Electric", "Steel"],
        preevolution: ["Magnemite"],
        evolution: [],
    },
    "Farfetch'd": {
        name: "Farfetch'd",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Doduo": {
        name: "Doduo",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Dodrio"],
    },
    "Dodrio": {
        name: "Dodrio",
        types: ["Normal", "Flying"],
        preevolution: ["Doduo"],
        evolution: [],
    },
    "Seel": {
        name: "Seel",
        types: ["Water"],
        preevolution: [],
        evolution: ["Dewgong"],
    },
    "Dewgong": {
        name: "Dewgong",
        types: ["Water", "Ice"],
        preevolution: ["Seel"],
        evolution: [],
    },
    "Grimer": {
        name: "Grimer",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Muk"],
    },
    "Muk": {
        name: "Muk",
        types: ["Poison"],
        preevolution: ["Grimer"],
        evolution: [],
    },
    "Shellder": {
        name: "Shellder",
        types: ["Water"],
        preevolution: [],
        evolution: ["Cloyster"],
    },
    "Cloyster": {
        name: "Cloyster",
        types: ["Water", "Ice"],
        preevolution: ["Shellder"],
        evolution: [],
    },
    "Gastly": {
        name: "Gastly",
        types: ["Ghost", "Poison"],
        preevolution: [],
        evolution: ["Haunter"],
    },
    "Haunter": {
        name: "Haunter",
        types: ["Ghost", "Poison"],
        preevolution: ["Gastly"],
        evolution: ["Gengar"],
    },
    "Gengar": {
        name: "Gengar",
        types: ["Ghost", "Poison"],
        preevolution: ["Haunter"],
        evolution: [],
    },
    "Onix": {
        name: "Onix",
        types: ["Rock", "Ground"],
        preevolution: [],
        evolution: ["Steelix"],
    },
    "Drowzee": {
        name: "Drowzee",
        types: ["Psychic"],
        preevolution: [],
        evolution: ["Hypno"],
    },
    "Hypno": {
        name: "Hypno",
        types: ["Psychic"],
        preevolution: ["Drowzee"],
        evolution: [],
    },
    "Krabby": {
        name: "Krabby",
        types: ["Water"],
        preevolution: [],
        evolution: ["Kingler"],
    },
    "Kingler": {
        name: "Kingler",
        types: ["Water"],
        preevolution: ["Krabby"],
        evolution: [],
    },
    "Voltorb": {
        name: "Voltorb",
        types: ["Electric"],
        preevolution: [],
        evolution: ["Electrode"],
    },
    "Electrode": {
        name: "Electrode",
        types: ["Electric"],
        preevolution: ["Voltorb"],
        evolution: [],
    },
    "Exeggcute": {
        name: "Exeggcute",
        types: ["Grass", "Psychic"],
        preevolution: [],
        evolution: ["Exeggutor"],
    },
    "Exeggutor": {
        name: "Exeggutor",
        types: ["Grass", "Psychic"],
        preevolution: ["Exeggcute"],
        evolution: [],
    },
    "Cubone": {
        name: "Cubone",
        types: ["Ground"],
        preevolution: [],
        evolution: ["Marowak"],
    },
    "Marowak": {
        name: "Marowak",
        types: ["Ground"],
        preevolution: ["Cubone"],
        evolution: [],
    },
    "Hitmonlee": {
        name: "Hitmonlee",
        types: ["Fighting"],
        preevolution: ["Tyrogue"],
        evolution: [],
    },
    "Hitmonchan": {
        name: "Hitmonchan",
        types: ["Fighting"],
        preevolution: ["Tyrogue"],
        evolution: [],
    },
    "Lickitung": {
        name: "Lickitung",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Koffing": {
        name: "Koffing",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Weezing"],
    },
    "Weezing": {
        name: "Weezing",
        types: ["Poison"],
        preevolution: ["Koffing"],
        evolution: [],
    },
    "Rhyhorn": {
        name: "Rhyhorn",
        types: ["Ground", "Rock"],
        preevolution: [],
        evolution: ["Rhydon"],
    },
    "Rhydon": {
        name: "Rhydon",
        types: ["Ground", "Rock"],
        preevolution: ["Rhyhorn"],
        evolution: [],
    },
    "Chansey": {
        name: "Chansey",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Blissey"],
    },
    "Tangela": {
        name: "Tangela",
        types: ["Grass"],
        preevolution: [],
        evolution: [],
    },
    "Kangaskhan": {
        name: "Kangaskhan",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Horsea": {
        name: "Horsea",
        types: ["Water"],
        preevolution: [],
        evolution: ["Seadra"],
    },
    "Seadra": {
        name: "Seadra",
        types: ["Water"],
        preevolution: ["Horsea"],
        evolution: ["Kingdra"],
    },
    "Goldeen": {
        name: "Goldeen",
        types: ["Water"],
        preevolution: [],
        evolution: ["Seaking"],
    },
    "Seaking": {
        name: "Seaking",
        types: ["Water"],
        preevolution: ["Goldeen"],
        evolution: [],
    },
    "Staryu": {
        name: "Staryu",
        types: ["Water"],
        preevolution: [],
        evolution: ["Starmie"],
    },
    "Starmie": {
        name: "Starmie",
        types: ["Water", "Psychic"],
        preevolution: ["Staryu"],
        evolution: [],
    },
    "Mr. Mime": {
        name: "Mr. Mime",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Scyther": {
        name: "Scyther",
        types: ["Bug", "Flying"],
        preevolution: [],
        evolution: ["Scizor"],
    },
    "Jynx": {
        name: "Jynx",
        types: ["Ice", "Psychic"],
        preevolution: ["Smoochum"],
        evolution: [],
    },
    "Electabuzz": {
        name: "Electabuzz",
        types: ["Electric"],
        preevolution: ["Elekid"],
        evolution: [],
    },
    "Magmar": {
        name: "Magmar",
        types: ["Fire"],
        preevolution: ["Magby"],
        evolution: [],
    },
    "Pinsir": {
        name: "Pinsir",
        types: ["Bug"],
        preevolution: [],
        evolution: [],
    },
    "Tauros": {
        name: "Tauros",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Magikarp": {
        name: "Magikarp",
        types: ["Water"],
        preevolution: [],
        evolution: ["Gyarados"],
    },
    "Gyarados": {
        name: "Gyarados",
        types: ["Water", "Flying"],
        preevolution: ["Magikarp"],
        evolution: [],
    },
    "Lapras": {
        name: "Lapras",
        types: ["Water", "Ice"],
        preevolution: [],
        evolution: [],
    },
    "Ditto": {
        name: "Ditto",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Eevee": {
        name: "Eevee",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon"],
    },
    "Vaporeon": {
        name: "Vaporeon",
        types: ["Water"],
        preevolution: ["Eevee"],
        evolution: [],
    },
    "Jolteon": {
        name: "Jolteon",
        types: ["Electric"],
        preevolution: ["Eevee"],
        evolution: [],
    },
    "Flareon": {
        name: "Flareon",
        types: ["Fire"],
        preevolution: ["Eevee"],
        evolution: [],
    },
    "Porygon": {
        name: "Porygon",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Porygon2"],
    },
    "Omanyte": {
        name: "Omanyte",
        types: ["Rock", "Water"],
        preevolution: [],
        evolution: ["Omastar"],
    },
    "Omastar": {
        name: "Omastar",
        types: ["Rock", "Water"],
        preevolution: ["Omanyte"],
        evolution: [],
    },
    "Kabuto": {
        name: "Kabuto",
        types: ["Rock", "Water"],
        preevolution: [],
        evolution: ["Kabutops"],
    },
    "Kabutops": {
        name: "Kabutops",
        types: ["Rock", "Water"],
        preevolution: ["Kabuto"],
        evolution: [],
    },
    "Aerodactyl": {
        name: "Aerodactyl",
        types: ["Rock", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Snorlax": {
        name: "Snorlax",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Articuno": {
        name: "Articuno",
        types: ["Ice", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Zapdos": {
        name: "Zapdos",
        types: ["Electric", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Moltres": {
        name: "Moltres",
        types: ["Fire", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Dratini": {
        name: "Dratini",
        types: ["Dragon"],
        preevolution: [],
        evolution: ["Dragonair"],
    },
    "Dragonair": {
        name: "Dragonair",
        types: ["Dragon"],
        preevolution: ["Dratini"],
        evolution: ["Dragonite"],
    },
    "Dragonite": {
        name: "Dragonite",
        types: ["Dragon", "Flying"],
        preevolution: ["Dragonair"],
        evolution: [],
    },
    "Mewtwo": {
        name: "Mewtwo",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Mew": {
        name: "Mew",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Chikorita": {
        name: "Chikorita",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Bayleef"],
    },
    "Bayleef": {
        name: "Bayleef",
        types: ["Grass"],
        preevolution: ["Chikorita"],
        evolution: ["Meganium"],
    },
    "Meganium": {
        name: "Meganium",
        types: ["Grass"],
        preevolution: ["Bayleef"],
        evolution: [],
    },
    "Cyndaquil": {
        name: "Cyndaquil",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Quilava"],
    },
    "Quilava": {
        name: "Quilava",
        types: ["Fire"],
        preevolution: ["Cyndaquil"],
        evolution: ["Typhlosion"],
    },
    "Typhlosion": {
        name: "Typhlosion",
        types: ["Fire"],
        preevolution: ["Quilava"],
        evolution: [],
    },
    "Totodile": {
        name: "Totodile",
        types: ["Water"],
        preevolution: [],
        evolution: ["Croconaw"],
    },
    "Croconaw": {
        name: "Croconaw",
        types: ["Water"],
        preevolution: ["Totodile"],
        evolution: ["Feraligatr"],
    },
    "Feraligatr": {
        name: "Feraligatr",
        types: ["Water"],
        preevolution: ["Croconaw"],
        evolution: [],
    },
    "Sentret": {
        name: "Sentret",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Furret"],
    },
    "Furret": {
        name: "Furret",
        types: ["Normal"],
        preevolution: ["Sentret"],
        evolution: [],
    },
    "Hoothoot": {
        name: "Hoothoot",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Noctowl"],
    },
    "Noctowl": {
        name: "Noctowl",
        types: ["Normal", "Flying"],
        preevolution: ["Hoothoot"],
        evolution: [],
    },
    "Ledyba": {
        name: "Ledyba",
        types: ["Bug", "Flying"],
        preevolution: [],
        evolution: ["Ledian"],
    },
    "Ledian": {
        name: "Ledian",
        types: ["Bug", "Flying"],
        preevolution: ["Ledyba"],
        evolution: [],
    },
    "Spinarak": {
        name: "Spinarak",
        types: ["Bug", "Poison"],
        preevolution: [],
        evolution: ["Ariados"],
    },
    "Ariados": {
        name: "Ariados",
        types: ["Bug", "Poison"],
        preevolution: ["Spinarak"],
        evolution: [],
    },
    "Crobat": {
        name: "Crobat",
        types: ["Poison", "Flying"],
        preevolution: ["Golbat"],
        evolution: [],
    },
    "Chinchou": {
        name: "Chinchou",
        types: ["Water", "Electric"],
        preevolution: [],
        evolution: ["Lanturn"],
    },
    "Lanturn": {
        name: "Lanturn",
        types: ["Water", "Electric"],
        preevolution: ["Chinchou"],
        evolution: [],
    },
    "Pichu": {
        name: "Pichu",
        types: ["Electric"],
        preevolution: [],
        evolution: ["Pikachu"],
    },
    "Cleffa": {
        name: "Cleffa",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Clefairy"],
    },
    "Igglybuff": {
        name: "Igglybuff",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Jigglypuff"],
    },
    "Togepi": {
        name: "Togepi",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Togetic"],
    },
    "Togetic": {
        name: "Togetic",
        types: ["Normal", "Flying"],
        preevolution: ["Togepi"],
        evolution: [],
    },
    "Natu": {
        name: "Natu",
        types: ["Psychic", "Flying"],
        preevolution: [],
        evolution: ["Xatu"],
    },
    "Xatu": {
        name: "Xatu",
        types: ["Psychic", "Flying"],
        preevolution: ["Natu"],
        evolution: [],
    },
    "Mareep": {
        name: "Mareep",
        types: ["Electric"],
        preevolution: [],
        evolution: ["Flaaffy"],
    },
    "Flaaffy": {
        name: "Flaaffy",
        types: ["Electric"],
        preevolution: ["Mareep"],
        evolution: ["Ampharos"],
    },
    "Ampharos": {
        name: "Ampharos",
        types: ["Electric"],
        preevolution: ["Flaaffy"],
        evolution: [],
    },
    "Bellossom": {
        name: "Bellossom",
        types: ["Grass"],
        preevolution: ["Gloom"],
        evolution: [],
    },
    "Marill": {
        name: "Marill",
        types: ["Water"],
        preevolution: ["Azurill"],
        evolution: ["Azumarill"],
    },
    "Azumarill": {
        name: "Azumarill",
        types: ["Water"],
        preevolution: ["Marill"],
        evolution: [],
    },
    "Sudowoodo": {
        name: "Sudowoodo",
        types: ["Rock"],
        preevolution: [],
        evolution: [],
    },
    "Politoed": {
        name: "Politoed",
        types: ["Water"],
        preevolution: ["Poliwhirl"],
        evolution: [],
    },
    "Hoppip": {
        name: "Hoppip",
        types: ["Grass", "Flying"],
        preevolution: [],
        evolution: ["Skiploom"],
    },
    "Skiploom": {
        name: "Skiploom",
        types: ["Grass", "Flying"],
        preevolution: ["Hoppip"],
        evolution: ["Jumpluff"],
    },
    "Jumpluff": {
        name: "Jumpluff",
        types: ["Grass", "Flying"],
        preevolution: ["Skiploom"],
        evolution: [],
    },
    "Aipom": {
        name: "Aipom",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Sunkern": {
        name: "Sunkern",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Sunflora"],
    },
    "Sunflora": {
        name: "Sunflora",
        types: ["Grass"],
        preevolution: ["Sunkern"],
        evolution: [],
    },
    "Yanma": {
        name: "Yanma",
        types: ["Bug", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Wooper": {
        name: "Wooper",
        types: ["Water", "Ground"],
        preevolution: [],
        evolution: ["Quagsire"],
    },
    "Quagsire": {
        name: "Quagsire",
        types: ["Water", "Ground"],
        preevolution: ["Wooper"],
        evolution: [],
    },
    "Espeon": {
        name: "Espeon",
        types: ["Psychic"],
        preevolution: ["Eevee"],
        evolution: [],
    },
    "Umbreon": {
        name: "Umbreon",
        types: ["Dark"],
        preevolution: ["Eevee"],
        evolution: [],
    },
    "Murkrow": {
        name: "Murkrow",
        types: ["Dark", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Slowking": {
        name: "Slowking",
        types: ["Water", "Psychic"],
        preevolution: ["Slowpoke"],
        evolution: [],
    },
    "Misdreavus": {
        name: "Misdreavus",
        types: ["Ghost"],
        preevolution: [],
        evolution: [],
    },
    "Unown": {
        name: "Unown",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Wobbuffet": {
        name: "Wobbuffet",
        types: ["Psychic"],
        preevolution: ["Wynaut"],
        evolution: [],
    },
    "Girafarig": {
        name: "Girafarig",
        types: ["Normal", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Pineco": {
        name: "Pineco",
        types: ["Bug"],
        preevolution: [],
        evolution: ["Forretress"],
    },
    "Forretress": {
        name: "Forretress",
        types: ["Bug", "Steel"],
        preevolution: ["Pineco"],
        evolution: [],
    },
    "Dunsparce": {
        name: "Dunsparce",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Gligar": {
        name: "Gligar",
        types: ["Ground", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Steelix": {
        name: "Steelix",
        types: ["Steel", "Ground"],
        preevolution: ["Onix"],
        evolution: [],
    },
    "Snubbull": {
        name: "Snubbull",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Granbull"],
    },
    "Granbull": {
        name: "Granbull",
        types: ["Normal"],
        preevolution: ["Snubbull"],
        evolution: [],
    },
    "Qwilfish": {
        name: "Qwilfish",
        types: ["Water", "Poison"],
        preevolution: [],
        evolution: [],
    },
    "Scizor": {
        name: "Scizor",
        types: ["Bug", "Steel"],
        preevolution: ["Scyther"],
        evolution: [],
    },
    "Shuckle": {
        name: "Shuckle",
        types: ["Bug", "Rock"],
        preevolution: [],
        evolution: [],
    },
    "Heracross": {
        name: "Heracross",
        types: ["Bug", "Fighting"],
        preevolution: [],
        evolution: [],
    },
    "Sneasel": {
        name: "Sneasel",
        types: ["Dark", "Ice"],
        preevolution: [],
        evolution: [],
    },
    "Teddiursa": {
        name: "Teddiursa",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Ursaring"],
    },
    "Ursaring": {
        name: "Ursaring",
        types: ["Normal"],
        preevolution: ["Teddiursa"],
        evolution: [],
    },
    "Slugma": {
        name: "Slugma",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Magcargo"],
    },
    "Magcargo": {
        name: "Magcargo",
        types: ["Fire", "Rock"],
        preevolution: ["Slugma"],
        evolution: [],
    },
    "Swinub": {
        name: "Swinub",
        types: ["Ice", "Ground"],
        preevolution: [],
        evolution: ["Piloswine"],
    },
    "Piloswine": {
        name: "Piloswine",
        types: ["Ice", "Ground"],
        preevolution: ["Swinub"],
        evolution: [],
    },
    "Corsola": {
        name: "Corsola",
        types: ["Water", "Rock"],
        preevolution: [],
        evolution: [],
    },
    "Remoraid": {
        name: "Remoraid",
        types: ["Water"],
        preevolution: [],
        evolution: ["Octillery"],
    },
    "Octillery": {
        name: "Octillery",
        types: ["Water"],
        preevolution: ["Remoraid"],
        evolution: [],
    },
    "Delibird": {
        name: "Delibird",
        types: ["Ice", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Mantine": {
        name: "Mantine",
        types: ["Water", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Skarmory": {
        name: "Skarmory",
        types: ["Steel", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Houndour": {
        name: "Houndour",
        types: ["Dark", "Fire"],
        preevolution: [],
        evolution: ["Houndoom"],
    },
    "Houndoom": {
        name: "Houndoom",
        types: ["Dark", "Fire"],
        preevolution: ["Houndour"],
        evolution: [],
    },
    "Kingdra": {
        name: "Kingdra",
        types: ["Water", "Dragon"],
        preevolution: ["Seadra"],
        evolution: [],
    },
    "Phanpy": {
        name: "Phanpy",
        types: ["Ground"],
        preevolution: [],
        evolution: ["Donphan"],
    },
    "Donphan": {
        name: "Donphan",
        types: ["Ground"],
        preevolution: ["Phanpy"],
        evolution: [],
    },
    "Porygon2": {
        name: "Porygon2",
        types: ["Normal"],
        preevolution: ["Porygon"],
        evolution: [],
    },
    "Stantler": {
        name: "Stantler",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Smeargle": {
        name: "Smeargle",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Tyrogue": {
        name: "Tyrogue",
        types: ["Fighting"],
        preevolution: [],
        evolution: ["Hitmonlee", "Hitmonchan", "Hitmontop"],
    },
    "Hitmontop": {
        name: "Hitmontop",
        types: ["Fighting"],
        preevolution: ["Tyrogue"],
        evolution: [],
    },
    "Smoochum": {
        name: "Smoochum",
        types: ["Ice", "Psychic"],
        preevolution: [],
        evolution: ["Jynx"],
    },
    "Elekid": {
        name: "Elekid",
        types: ["Electric"],
        preevolution: [],
        evolution: ["Electabuzz"],
    },
    "Magby": {
        name: "Magby",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Magmar"],
    },
    "Miltank": {
        name: "Miltank",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Blissey": {
        name: "Blissey",
        types: ["Normal"],
        preevolution: ["Chansey"],
        evolution: [],
    },
    "Raikou": {
        name: "Raikou",
        types: ["Electric"],
        preevolution: [],
        evolution: [],
    },
    "Entei": {
        name: "Entei",
        types: ["Fire"],
        preevolution: [],
        evolution: [],
    },
    "Suicune": {
        name: "Suicune",
        types: ["Water"],
        preevolution: [],
        evolution: [],
    },
    "Larvitar": {
        name: "Larvitar",
        types: ["Rock", "Ground"],
        preevolution: [],
        evolution: ["Pupitar"],
    },
    "Pupitar": {
        name: "Pupitar",
        types: ["Rock", "Ground"],
        preevolution: ["Larvitar"],
        evolution: ["Tyranitar"],
    },
    "Tyranitar": {
        name: "Tyranitar",
        types: ["Rock", "Dark"],
        preevolution: ["Pupitar"],
        evolution: [],
    },
    "Lugia": {
        name: "Lugia",
        types: ["Psychic", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Ho-Oh": {
        name: "Ho-Oh",
        types: ["Fire", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Celebi": {
        name: "Celebi",
        types: ["Psychic", "Grass"],
        preevolution: [],
        evolution: [],
    },
    "Treecko": {
        name: "Treecko",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Grovyle"],
    },
    "Grovyle": {
        name: "Grovyle",
        types: ["Grass"],
        preevolution: ["Treecko"],
        evolution: ["Sceptile"],
    },
    "Sceptile": {
        name: "Sceptile",
        types: ["Grass"],
        preevolution: ["Grovyle"],
        evolution: [],
    },
    "Torchic": {
        name: "Torchic",
        types: ["Fire"],
        preevolution: [],
        evolution: ["Combusken"],
    },
    "Combusken": {
        name: "Combusken",
        types: ["Fire", "Fighting"],
        preevolution: ["Torchic"],
        evolution: ["Blaziken"],
    },
    "Blaziken": {
        name: "Blaziken",
        types: ["Fire", "Fighting"],
        preevolution: ["Combusken"],
        evolution: [],
    },
    "Mudkip": {
        name: "Mudkip",
        types: ["Water"],
        preevolution: [],
        evolution: ["Marshtomp"],
    },
    "Marshtomp": {
        name: "Marshtomp",
        types: ["Water", "Ground"],
        preevolution: ["Mudkip"],
        evolution: ["Swampert"],
    },
    "Swampert": {
        name: "Swampert",
        types: ["Water", "Ground"],
        preevolution: ["Marshtomp"],
        evolution: [],
    },
    "Poochyena": {
        name: "Poochyena",
        types: ["Dark"],
        preevolution: [],
        evolution: ["Mightyena"],
    },
    "Mightyena": {
        name: "Mightyena",
        types: ["Dark"],
        preevolution: ["Poochyena"],
        evolution: [],
    },
    "Zigzagoon": {
        name: "Zigzagoon",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Linoone"],
    },
    "Linoone": {
        name: "Linoone",
        types: ["Normal"],
        preevolution: ["Zigzagoon"],
        evolution: [],
    },
    "Wurmple": {
        name: "Wurmple",
        types: ["Bug"],
        preevolution: [],
        evolution: ["Silcoon", "Cascoon"],
    },
    "Silcoon": {
        name: "Silcoon",
        types: ["Bug"],
        preevolution: ["Wurmple"],
        evolution: ["Beautifly"],
    },
    "Beautifly": {
        name: "Beautifly",
        types: ["Bug", "Flying"],
        preevolution: ["Silcoon"],
        evolution: [],
    },
    "Cascoon": {
        name: "Cascoon",
        types: ["Bug"],
        preevolution: ["Wurmple"],
        evolution: ["Dustox"],
    },
    "Dustox": {
        name: "Dustox",
        types: ["Bug", "Poison"],
        preevolution: ["Cascoon"],
        evolution: [],
    },
    "Lotad": {
        name: "Lotad",
        types: ["Water", "Grass"],
        preevolution: [],
        evolution: ["Lombre"],
    },
    "Lombre": {
        name: "Lombre",
        types: ["Water", "Grass"],
        preevolution: ["Lotad"],
        evolution: ["Ludicolo"],
    },
    "Ludicolo": {
        name: "Ludicolo",
        types: ["Water", "Grass"],
        preevolution: ["Lombre"],
        evolution: [],
    },
    "Seedot": {
        name: "Seedot",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Nuzleaf"],
    },
    "Nuzleaf": {
        name: "Nuzleaf",
        types: ["Grass", "Dark"],
        preevolution: ["Seedot"],
        evolution: ["Shiftry"],
    },
    "Shiftry": {
        name: "Shiftry",
        types: ["Grass", "Dark"],
        preevolution: ["Nuzleaf"],
        evolution: [],
    },
    "Taillow": {
        name: "Taillow",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Swellow"],
    },
    "Swellow": {
        name: "Swellow",
        types: ["Normal", "Flying"],
        preevolution: ["Taillow"],
        evolution: [],
    },
    "Wingull": {
        name: "Wingull",
        types: ["Water", "Flying"],
        preevolution: [],
        evolution: ["Pelipper"],
    },
    "Pelipper": {
        name: "Pelipper",
        types: ["Water", "Flying"],
        preevolution: ["Wingull"],
        evolution: [],
    },
    "Ralts": {
        name: "Ralts",
        types: ["Psychic"],
        preevolution: [],
        evolution: ["Kirlia"],
    },
    "Kirlia": {
        name: "Kirlia",
        types: ["Psychic"],
        preevolution: ["Ralts"],
        evolution: ["Gardevoir"],
    },
    "Gardevoir": {
        name: "Gardevoir",
        types: ["Psychic"],
        preevolution: ["Kirlia"],
        evolution: [],
    },
    "Surskit": {
        name: "Surskit",
        types: ["Bug", "Water"],
        preevolution: [],
        evolution: ["Masquerain"],
    },
    "Masquerain": {
        name: "Masquerain",
        types: ["Bug", "Flying"],
        preevolution: ["Surskit"],
        evolution: [],
    },
    "Shroomish": {
        name: "Shroomish",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Breloom"],
    },
    "Breloom": {
        name: "Breloom",
        types: ["Grass", "Fighting"],
        preevolution: ["Shroomish"],
        evolution: [],
    },
    "Slakoth": {
        name: "Slakoth",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Vigoroth"],
    },
    "Vigoroth": {
        name: "Vigoroth",
        types: ["Normal"],
        preevolution: ["Slakoth"],
        evolution: ["Slaking"],
    },
    "Slaking": {
        name: "Slaking",
        types: ["Normal"],
        preevolution: ["Vigoroth"],
        evolution: [],
    },
    "Nincada": {
        name: "Nincada",
        types: ["Bug", "Ground"],
        preevolution: [],
        evolution: ["Ninjask", "Shedinja"],
    },
    "Ninjask": {
        name: "Ninjask",
        types: ["Bug", "Flying"],
        preevolution: ["Nincada"],
        evolution: [],
    },
    "Shedinja": {
        name: "Shedinja",
        types: ["Bug", "Ghost"],
        preevolution: ["Nincada"],
        evolution: [],
    },
    "Whismur": {
        name: "Whismur",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Loudred"],
    },
    "Loudred": {
        name: "Loudred",
        types: ["Normal"],
        preevolution: ["Whismur"],
        evolution: ["Exploud"],
    },
    "Exploud": {
        name: "Exploud",
        types: ["Normal"],
        preevolution: ["Loudred"],
        evolution: [],
    },
    "Makuhita": {
        name: "Makuhita",
        types: ["Fighting"],
        preevolution: [],
        evolution: ["Hariyama"],
    },
    "Hariyama": {
        name: "Hariyama",
        types: ["Fighting"],
        preevolution: ["Makuhita"],
        evolution: [],
    },
    "Azurill": {
        name: "Azurill",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Marill"],
    },
    "Nosepass": {
        name: "Nosepass",
        types: ["Rock"],
        preevolution: [],
        evolution: [],
    },
    "Skitty": {
        name: "Skitty",
        types: ["Normal"],
        preevolution: [],
        evolution: ["Delcatty"],
    },
    "Delcatty": {
        name: "Delcatty",
        types: ["Normal"],
        preevolution: ["Skitty"],
        evolution: [],
    },
    "Sableye": {
        name: "Sableye",
        types: ["Dark", "Ghost"],
        preevolution: [],
        evolution: [],
    },
    "Mawile": {
        name: "Mawile",
        types: ["Steel"],
        preevolution: [],
        evolution: [],
    },
    "Aron": {
        name: "Aron",
        types: ["Steel", "Rock"],
        preevolution: [],
        evolution: ["Lairon"],
    },
    "Lairon": {
        name: "Lairon",
        types: ["Steel", "Rock"],
        preevolution: ["Aron"],
        evolution: ["Aggron"],
    },
    "Aggron": {
        name: "Aggron",
        types: ["Steel", "Rock"],
        preevolution: ["Lairon"],
        evolution: [],
    },
    "Meditite": {
        name: "Meditite",
        types: ["Fighting", "Psychic"],
        preevolution: [],
        evolution: ["Medicham"],
    },
    "Medicham": {
        name: "Medicham",
        types: ["Fighting", "Psychic"],
        preevolution: ["Meditite"],
        evolution: [],
    },
    "Electrike": {
        name: "Electrike",
        types: ["Electric"],
        preevolution: [],
        evolution: ["Manectric"],
    },
    "Manectric": {
        name: "Manectric",
        types: ["Electric"],
        preevolution: ["Electrike"],
        evolution: [],
    },
    "Plusle": {
        name: "Plusle",
        types: ["Electric"],
        preevolution: [],
        evolution: [],
    },
    "Minun": {
        name: "Minun",
        types: ["Electric"],
        preevolution: [],
        evolution: [],
    },
    "Volbeat": {
        name: "Volbeat",
        types: ["Bug"],
        evolution: [],
    },
    "Illumise": {
        name: "Illumise",
        types: ["Bug"],
        preevolution: [],
        evolution: [],
    },
    "Roselia": {
        name: "Roselia",
        types: ["Grass", "Poison"],
        preevolution: [],
        evolution: [],
    },
    "Gulpin": {
        name: "Gulpin",
        types: ["Poison"],
        preevolution: [],
        evolution: ["Swalot"],
    },
    "Swalot": {
        name: "Swalot",
        types: ["Poison"],
        preevolution: ["Gulpin"],
        evolution: [],
    },
    "Carvanha": {
        name: "Carvanha",
        types: ["Water", "Dark"],
        preevolution: [],
        evolution: ["Sharpedo"],
    },
    "Sharpedo": {
        name: "Sharpedo",
        types: ["Water", "Dark"],
        preevolution: ["Carvanha"],
        evolution: [],
    },
    "Wailmer": {
        name: "Wailmer",
        types: ["Water"],
        preevolution: [],
        evolution: ["Wailord"],
    },
    "Wailord": {
        name: "Wailord",
        types: ["Water"],
        preevolution: ["Wailmer"],
        evolution: [],
    },
    "Numel": {
        name: "Numel",
        types: ["Fire", "Ground"],
        preevolution: [],
        evolution: ["Camerupt"],
    },
    "Camerupt": {
        name: "Camerupt",
        types: ["Fire", "Ground"],
        preevolution: ["Numel"],
        evolution: [],
    },
    "Torkoal": {
        name: "Torkoal",
        types: ["Fire"],
        preevolution: [],
        evolution: [],
    },
    "Spoink": {
        name: "Spoink",
        types: ["Psychic"],
        preevolution: [],
        evolution: ["Grumpig"],
    },
    "Grumpig": {
        name: "Grumpig",
        types: ["Psychic"],
        preevolution: ["Spoink"],
        evolution: [],
    },
    "Spinda": {
        name: "Spinda",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Trapinch": {
        name: "Trapinch",
        types: ["Ground"],
        preevolution: [],
        evolution: ["Vibrava"],
    },
    "Vibrava": {
        name: "Vibrava",
        types: ["Ground", "Dragon"],
        preevolution: ["Trapinch"],
        evolution: ["Flygon"],
    },
    "Flygon": {
        name: "Flygon",
        types: ["Ground", "Dragon"],
        preevolution: ["Vibrava"],
        evolution: [],
    },
    "Cacnea": {
        name: "Cacnea",
        types: ["Grass"],
        preevolution: [],
        evolution: ["Cacturne"],
    },
    "Cacturne": {
        name: "Cacturne",
        types: ["Grass", "Dark"],
        preevolution: ["Cacnea"],
        evolution: [],
    },
    "Swablu": {
        name: "Swablu",
        types: ["Normal", "Flying"],
        preevolution: [],
        evolution: ["Altaria"],
    },
    "Altaria": {
        name: "Altaria",
        types: ["Dragon", "Flying"],
        preevolution: ["Swablu"],
        evolution: [],
    },
    "Zangoose": {
        name: "Zangoose",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Seviper": {
        name: "Seviper",
        types: ["Poison"],
        preevolution: [],
        evolution: [],
    },
    "Lunatone": {
        name: "Lunatone",
        types: ["Rock", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Solrock": {
        name: "Solrock",
        types: ["Rock", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Barboach": {
        name: "Barboach",
        types: ["Water", "Ground"],
        preevolution: [],
        evolution: ["Whiscash"],
    },
    "Whiscash": {
        name: "Whiscash",
        types: ["Water", "Ground"],
        preevolution: ["Barboach"],
        evolution: [],
    },
    "Corphish": {
        name: "Corphish",
        types: ["Water"],
        preevolution: [],
        evolution: ["Crawdaunt"],
    },
    "Crawdaunt": {
        name: "Crawdaunt",
        types: ["Water", "Dark"],
        preevolution: ["Corphish"],
        evolution: [],
    },
    "Baltoy": {
        name: "Baltoy",
        types: ["Ground", "Psychic"],
        preevolution: [],
        evolution: ["Claydol"],
    },
    "Claydol": {
        name: "Claydol",
        types: ["Ground", "Psychic"],
        preevolution: ["Baltoy"],
        evolution: [],
    },
    "Lileep": {
        name: "Lileep",
        types: ["Rock", "Grass"],
        preevolution: [],
        evolution: ["Cradily"],
    },
    "Cradily": {
        name: "Cradily",
        types: ["Rock", "Grass"],
        preevolution: ["Lileep"],
        evolution: [],
    },
    "Anorith": {
        name: "Anorith",
        types: ["Rock", "Bug"],
        preevolution: [],
        evolution: ["Armaldo"],
    },
    "Armaldo": {
        name: "Armaldo",
        types: ["Rock", "Bug"],
        preevolution: ["Anorith"],
        evolution: [],
    },
    "Feebas": {
        name: "Feebas",
        types: ["Water"],
        preevolution: [],
        evolution: ["Milotic"],
    },
    "Milotic": {
        name: "Milotic",
        types: ["Water"],
        preevolution: ["Feebas"],
        evolution: [],
    },
    "Castform": {
        name: "Castform",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Kecleon": {
        name: "Kecleon",
        types: ["Normal"],
        preevolution: [],
        evolution: [],
    },
    "Shuppet": {
        name: "Shuppet",
        types: ["Ghost"],
        preevolution: [],
        evolution: ["Banette"],
    },
    "Banette": {
        name: "Banette",
        types: ["Ghost"],
        preevolution: ["Shuppet"],
        evolution: [],
    },
    "Duskull": {
        name: "Duskull",
        types: ["Ghost"],
        preevolution: [],
        evolution: ["Dusclops"],
    },
    "Dusclops": {
        name: "Dusclops",
        types: ["Ghost"],
        preevolution: ["Duskull"],
        evolution: [],
    },
    "Tropius": {
        name: "Tropius",
        types: ["Grass", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Chimecho": {
        name: "Chimecho",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Absol": {
        name: "Absol",
        types: ["Dark"],
        preevolution: [],
        evolution: [],
    },
    "Wynaut": {
        name: "Wynaut",
        types: ["Psychic"],
        preevolution: [],
        evolution: ["Wobbuffet"],
    },
    "Snorunt": {
        name: "Snorunt",
        types: ["Ice"],
        preevolution: [],
        evolution: ["Glalie"],
    },
    "Glalie": {
        name: "Glalie",
        types: ["Ice"],
        preevolution: ["Snorunt"],
        evolution: [],
    },
    "Spheal": {
        name: "Spheal",
        types: ["Ice", "Water"],
        preevolution: [],
        evolution: ["Sealeo"],
    },
    "Sealeo": {
        name: "Sealeo",
        types: ["Ice", "Water"],
        preevolution: ["Spheal"],
        evolution: ["Walrein"],
    },
    "Walrein": {
        name: "Walrein",
        types: ["Ice", "Water"],
        preevolution: ["Sealeo"],
        evolution: [],
    },
    "Clamperl": {
        name: "Clamperl",
        types: ["Water"],
        preevolution: [],
        evolution: ["Huntail", "Gorebyss"],
    },
    "Huntail": {
        name: "Huntail",
        types: ["Water"],
        preevolution: ["Clamperl"],
        evolution: [],
    },
    "Gorebyss": {
        name: "Gorebyss",
        types: ["Water"],
        preevolution: ["Clamperl"],
        evolution: [],
    },
    "Relicanth": {
        name: "Relicanth",
        types: ["Water", "Rock"],
        preevolution: [],
        evolution: [],
    },
    "Luvdisc": {
        name: "Luvdisc",
        types: ["Water"],
        preevolution: [],
        evolution: [],
    },
    "Bagon": {
        name: "Bagon",
        types: ["Dragon"],
        preevolution: [],
        evolution: ["Shelgon"],
    },
    "Shelgon": {
        name: "Shelgon",
        types: ["Dragon"],
        preevolution: ["Bagon"],
        evolution: ["Salamence"],
    },
    "Salamence": {
        name: "Salamence",
        types: ["Dragon", "Flying"],
        preevolution: ["Shelgon"],
        evolution: [],
    },
    "Beldum": {
        name: "Beldum",
        types: ["Steel", "Psychic"],
        preevolution: [],
        evolution: ["Metang"],
    },
    "Metang": {
        name: "Metang",
        types: ["Steel", "Psychic"],
        preevolution: ["Beldum"],
        evolution: ["Metagross"],
    },
    "Metagross": {
        name: "Metagross",
        types: ["Steel", "Psychic"],
        preevolution: ["Metang"],
        evolution: [],
    },
    "Regirock": {
        name: "Regirock",
        types: ["Rock"],
        preevolution: [],
        evolution: [],
    },
    "Regice": {
        name: "Regice",
        types: ["Ice"],
        preevolution: [],
        evolution: [],
    },
    "Registeel": {
        name: "Registeel",
        types: ["Steel"],
        preevolution: [],
        evolution: [],
    },
    "Latias": {
        name: "Latias",
        types: ["Dragon", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Latios": {
        name: "Latios",
        types: ["Dragon", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Kyogre": {
        name: "Kyogre",
        types: ["Water"],
        preevolution: [],
        evolution: [],
    },
    "Groudon": {
        name: "Groudon",
        types: ["Ground"],
        preevolution: [],
        evolution: [],
    },
    "Rayquaza": {
        name: "Rayquaza",
        types: ["Dragon", "Flying"],
        preevolution: [],
        evolution: [],
    },
    "Jirachi": {
        name: "Jirachi",
        types: ["Steel", "Psychic"],
        preevolution: [],
        evolution: [],
    },
    "Deoxys": {
        name: "Deoxys",
        types: ["Psychic"],
        preevolution: [],
        evolution: [],
    },
}

const Type = {
    "Normal": {
        name: "Normal",
        gummies: {
            "White": 7,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 4,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 3,
            "Green": 3,
            "Gray": 3,
            "Purple": 1,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Fire": {
        name: "Fire",
        gummies: {
            "White": 3,
            "Red": 7,
            "Blue": 4,
            "Grass": 2,
            "Yellow": 3,
            "Clear": 2,
            "Orange": 3,
            "Pink": 3,
            "Brown": 4,
            "Sky": 3,
            "Gold": 3,
            "Green": 2,
            "Gray": 4,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 2,
        },
    },
    "Water": {
        name: "Water",
        gummies: {
            "White": 3,
            "Red": 2,
            "Blue": 7,
            "Grass": 4,
            "Yellow": 4,
            "Clear": 2,
            "Orange": 3,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 3,
            "Green": 3,
            "Gray": 3,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 2,
        },
    },
    "Grass": {
        name: "Grass",
        gummies: {
            "White": 3,
            "Red": 4,
            "Blue": 2,
            "Grass": 7,
            "Yellow": 2,
            "Clear": 4,
            "Orange": 3,
            "Pink": 4,
            "Brown": 2,
            "Sky": 4,
            "Gold": 3,
            "Green": 4,
            "Gray": 3,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Electric": {
        name: "Electric",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 7,
            "Clear": 3,
            "Orange": 3,
            "Pink": 3,
            "Brown": 4,
            "Sky": 2,
            "Gold": 3,
            "Green": 3,
            "Gray": 3,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 2,
        },
    },
    "Ice": {
        name: "Ice",
        gummies: {
            "White": 3,
            "Red": 4,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 7,
            "Orange": 4,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 3,
            "Green": 3,
            "Gray": 4,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 4,
        },
    },
    "Fighting": {
        name: "Fighting",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 7,
            "Pink": 3,
            "Brown": 3,
            "Sky": 4,
            "Gold": 4,
            "Green": 2,
            "Gray": 2,
            "Purple": 3,
            "Royal": 3,
            "Black": 2,
            "Silver": 3,
        },
    },
    "Poison": {
        name: "Poison",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 2,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 2,
            "Pink": 7,
            "Brown": 4,
            "Sky": 3,
            "Gold": 4,
            "Green": 2,
            "Gray": 3,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Ground": {
        name: "Ground",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 4,
            "Grass": 4,
            "Yellow": 1,
            "Clear": 4,
            "Orange": 3,
            "Pink": 2,
            "Brown": 7,
            "Sky": 3,
            "Gold": 3,
            "Green": 3,
            "Gray": 2,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Flying": {
        name: "Flying",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 2,
            "Yellow": 4,
            "Clear": 4,
            "Orange": 2,
            "Pink": 3,
            "Brown": 1,
            "Sky": 7,
            "Gold": 3,
            "Green": 2,
            "Gray": 4,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Psychic": {
        name: "Psychic",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 2,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 7,
            "Green": 4,
            "Gray": 3,
            "Purple": 4,
            "Royal": 3,
            "Black": 4,
            "Silver": 3,
        },
    },
    "Bug": {
        name: "Bug",
        gummies: {
            "White": 3,
            "Red": 4,
            "Blue": 3,
            "Grass": 2,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 2,
            "Pink": 3,
            "Brown": 2,
            "Sky": 4,
            "Gold": 3,
            "Green": 7,
            "Gray": 4,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Rock": {
        name: "Rock",
        gummies: {
            "White": 2,
            "Red": 2,
            "Blue": 4,
            "Grass": 4,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 4,
            "Pink": 2,
            "Brown": 4,
            "Sky": 2,
            "Gold": 3,
            "Green": 3,
            "Gray": 7,
            "Purple": 3,
            "Royal": 3,
            "Black": 3,
            "Silver": 4,
        },
    },
    "Ghost": {
        name: "Ghost",
        gummies: {
            "White": 1,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 1,
            "Pink": 2,
            "Brown": 3,
            "Sky": 3,
            "Gold": 3,
            "Green": 2,
            "Gray": 3,
            "Purple": 7,
            "Royal": 3,
            "Black": 4,
            "Silver": 3,
        },
    },
    "Dragon": {
        name: "Dragon",
        gummies: {
            "White": 3,
            "Red": 2,
            "Blue": 2,
            "Grass": 2,
            "Yellow": 2,
            "Clear": 4,
            "Orange": 3,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 3,
            "Green": 3,
            "Gray": 3,
            "Purple": 3,
            "Royal": 7,
            "Black": 3,
            "Silver": 3,
        },
    },
    "Dark": {
        name: "Dark",
        gummies: {
            "White": 3,
            "Red": 3,
            "Blue": 3,
            "Grass": 3,
            "Yellow": 3,
            "Clear": 3,
            "Orange": 4,
            "Pink": 3,
            "Brown": 3,
            "Sky": 3,
            "Gold": 1,
            "Green": 4,
            "Gray": 3,
            "Purple": 2,
            "Royal": 3,
            "Black": 7,
            "Silver": 3,
        },
    },
    "Steel": {
        name: "Steel",
        gummies: {
            "White": 2,
            "Red": 4,
            "Blue": 3,
            "Grass": 2,
            "Yellow": 3,
            "Clear": 2,
            "Orange": 4,
            "Pink": 1,
            "Brown": 4,
            "Sky": 2,
            "Gold": 2,
            "Green": 2,
            "Gray": 2,
            "Purple": 2,
            "Royal": 2,
            "Black": 2,
            "Silver": 7,
        },
    },
}

const Gummi = [
    "White",
    "Red",
    "Blue",
    "Grass",
    "Yellow",
    "Clear",
    "Orange",
    "Pink",
    "Brown",
    "Sky",
    "Gold",
    "Green",
    "Gray",
    "Purple",
    "Royal",
    "Black",
    "Silver",
]
